<template>
  <div id="about" class="ion-page">

    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-toggle>
            <ion-button>
              <ion-icon slot="icon-only" name="menu"></ion-icon>
            </ion-button>
          </ion-menu-toggle>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>

    <ion-content class="ion-padding">
      <ion-text>
        <h1>About</h1>
        <p class="text">
          The mydata.energy Dashboard provides a visual way to view the data being generated by your Wattwatchers devices.
          <br><br>
          It is optimised for residential households that have solar generation installed, however a number of our residential and commercial customers without solar are also using the app.
        </p>
      </ion-text>
    </ion-content>

  </div>
</template>

<script>
  export default {
    name: 'about'
  }
</script>

<style scoped>
  .text {
    text-align: left;
  }
</style>